apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongo"
  selector:
    matchLabels:
      app: mongodb
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ .Values.replicas | default 1 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
        app.kubernetes.io/component: {{ include "mongodb.name" . }}
        app.kubernetes.io/version: "{{ .Values.image.tag }}"
        helm.sh/chart: {{ include "mongodb.chart" . }}
    spec:
      {{- list .Values | dict "context" . "indent" 6 "bases" | include "keptn.image.pullSecrets" }}
      serviceAccountName: keptn-default
      securityContext:
        fsGroup: 184
      terminationGracePeriodSeconds: 10
      containers:
        - image: {{ dict "space" .Values "context" . | include "keptn.image.name" }}
          name: mongodb
          args:
            - run-mongod-replication
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          volumeMounts:
            - mountPath: /var/lib/mongodb/data
              name: mongodata
          env:
            - name: MONGODB_DATABASE
              value: "keptn"
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: password
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: admin_password
            - name: MONGODB_REPLICA_NAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: replica_set
            - name: MONGODB_KEYFILE_VALUE
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: keyfile_value
            - name: MONGODB_SERVICE_NAME
              value: mongo
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/initialized
          securityContext:
            runAsNonRoot: true
            runAsUser: 184
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata