{{- $mongoUser := "user" | b64enc | quote -}}
{{- if .Values.mongodb.user -}}
{{- $mongoUser = .Values.mongodb.user | b64enc | quote -}}
{{- end -}}

{{- $mongoReplicaSet := "keptn-rs" | b64enc | quote -}}
{{- if .Values.mongodb.user -}}
{{- $mongoReplicaSet = .Values.mongodb.replicaSet | b64enc | quote -}}
{{- end -}}

{{- $mongoPassword := (randAlphaNum 20) | b64enc | quote -}}
{{- if .Values.mongodb.password -}}
{{- $mongoPassword = .Values.mongodb.password | b64enc | quote -}}
{{- end -}}

{{- $mongoAdminPassword := (randAlphaNum 45) | b64enc | quote -}}
{{- if .Values.mongodb.adminPassword -}}
{{- $mongoAdminPassword = .Values.mongodb.adminPassword | b64enc | quote  -}}
{{- end -}}

{{- $mongoKeyFileValue := (randAlphaNum 45) | b64enc | quote -}}
{{- if .Values.mongodb.keyFileValue -}}
{{- $mongoKeyFileValue = .Values.mongodb.keyFileValue | b64enc | quote  -}}
{{- end -}}

{{- $mongosecret := (lookup "v1" "Secret" .Release.Namespace "mongodb-credentials") -}}

{{- if $mongosecret -}}
{{- $mongoUser = index $mongosecret.data "user" -}}
{{- end -}}

{{- if $mongosecret -}}
{{- $mongoPassword = index $mongosecret.data "password" -}}
{{- end -}}

{{- if $mongosecret -}}
{{- $mongoAdminPassword = index $mongosecret.data "admin_password" -}}
{{- end -}}

{{- if $mongosecret -}}
{{- $mongoKeyFileValue = index $mongosecret.data "keyfile_value" -}}
{{- end -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  labels:
    app.kubernetes.io/name: mongodb-credentials
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
    helm.sh/chart: {{ include "control-plane.chart" . }}     
type: Opaque
data:
  user: {{ $mongoUser }}
  password: {{ $mongoPassword }}
  admin_password: {{ $mongoAdminPassword }}
  keyfile_value: {{ $mongoKeyFileValue }}
  replica_set: {{ $mongoReplicaSet }}
