apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: keptn/statistics-service
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - deploy/service.yaml
